from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy.orm import Session

from src.auth import require_role
from src.context import base_context
from src.db import get_db
from src.models import Event, User
from src.templating import templates

router = APIRouter()


import random
from collections import Counter, defaultdict

from fastapi import Form

from src.models import (
    AuditLog,
    EventMember,
    JudgeTrack,
    PairwiseComparison,
    Project,
    RubricCriteria,
    Score,
    Track,
)
from src.timeutil import utcnow


def compute_pairwise_elo_for_judge(db: Session, event_id: str, judge_id: str):
    """
    Computes Bradley-Terry ELO ratings, wins, and losses for projects evaluated by judge_id.
    Excludes any projects from which the judge has recused due to conflict of interest.
    """
    comps = (
        db.query(PairwiseComparison)
        .filter_by(event_id=event_id, judge_id=judge_id)
        .order_by(PairwiseComparison.created_at)
        .all()
    )
    if not comps:
        return {}

    # Get set of recused project IDs for this judge to exclude them
    recused_pids = set(
        s.project_id
        for s in db.query(Score)
        .filter_by(event_id=event_id, judge_id=judge_id, conflict_of_interest=True)
        .all()
    )

    evaluated_project_ids = set()
    for c in comps:
        if (
            c.winner_project_id not in recused_pids
            and c.loser_project_id not in recused_pids
        ):
            evaluated_project_ids.add(c.winner_project_id)
            evaluated_project_ids.add(c.loser_project_id)

    if not evaluated_project_ids:
        return {}

    stats = {
        pid: {"elo": 1500.0, "wins": 0, "losses": 0, "score": 7}
        for pid in evaluated_project_ids
    }
    K = 32

    for c in comps:
        w_id = c.winner_project_id
        l_id = c.loser_project_id
        if w_id in stats and l_id in stats:
            stats[w_id]["wins"] += 1
            stats[l_id]["losses"] += 1

            rw = stats[w_id]["elo"]
            rl = stats[l_id]["elo"]

            p_win = 1.0 / (1.0 + 10 ** ((rl - rw) / 400.0))
            p_lose = 1.0 / (1.0 + 10 ** ((rw - rl) / 400.0))

            stats[w_id]["elo"] = rw + K * (1.0 - p_win)
            stats[l_id]["elo"] = rl + K * (0.0 - p_lose)

    for pid, data in stats.items():
        # Baseline 1500 -> 7/10. 1400 -> 4/10. 1600 -> 10/10. Clamped to [1, 10].
        raw_val = 7.0 + (data["elo"] - 1500.0) / 33.0
        data["score"] = max(1, min(10, int(round(raw_val))))

    return stats


def sync_pairwise_scores(db: Session, event_id: str, judge_id: str):
    """
    Synchronizes PairwiseComparison results into the Score table for the judge.
    For each evaluated project, creates or updates Score records across event criteria.
    Never overwrites projects where the judge has recused with conflict_of_interest.
    """
    stats = compute_pairwise_elo_for_judge(db, event_id, judge_id)
    if not stats:
        return stats

    criteria = db.query(RubricCriteria).filter_by(event_id=event_id).all()
    if not criteria:
        default_crit = RubricCriteria(
            id=f"{event_id}:overall",
            event_id=event_id,
            name="Overall Quality",
            weight=100,
        )
        db.add(default_crit)
        db.flush()
        criteria = [default_crit]

    for pid, data in stats.items():
        score_val = data["score"]
        elo_val = int(round(data["elo"]))
        comment_str = f"Pairwise ELO: {elo_val} ({data['wins']}W - {data['losses']}L)"

        for crit in criteria:
            existing = (
                db.query(Score)
                .filter_by(
                    event_id=event_id,
                    judge_id=judge_id,
                    project_id=pid,
                    criteria_id=crit.id,
                )
                .first()
            )

            if existing:
                # Never overwrite a project marked as conflict of interest / recused
                if existing.conflict_of_interest:
                    continue
                # Update if auto-generated by pairwise or empty comment
                if not existing.comment or existing.comment.startswith("Pairwise ELO:"):
                    existing.value = score_val
                    existing.comment = comment_str
            else:
                db.add(
                    Score(
                        event_id=event_id,
                        judge_id=judge_id,
                        project_id=pid,
                        criteria_id=crit.id,
                        value=score_val,
                        comment=comment_str,
                        conflict_of_interest=False,
                    )
                )

    db.commit()
    return stats


def get_judge_assigned_projects(
    db: Session, event_id: str, user: User
) -> list[Project]:
    """
    Returns the list of active (non-draft, non-disqualified) projects assigned to the user
    for the given event. If the user is an organizer/admin without specific track assignments,
    or the event has no tracks, all active projects in the event are returned.
    """
    judge_tracks = (
        db.query(JudgeTrack).filter_by(event_id=event_id, judge_id=user.id).all()
    )
    track_ids = [jt.track_id for jt in judge_tracks]
    event_has_tracks = db.query(Track).filter_by(event_id=event_id).first() is not None

    membership = (
        db.query(EventMember).filter_by(event_id=event_id, user_id=user.id).first()
    )
    user_role = membership.role if membership else getattr(user, "role", None)

    if user_role in ("organizer", "admin") and not track_ids:
        return (
            db.query(Project)
            .filter(
                Project.event_id == event_id,
                Project.is_draft.is_(False),
                Project.is_disqualified.is_(False),
            )
            .order_by(Project.id)
            .all()
        )
    elif not event_has_tracks:
        return (
            db.query(Project)
            .filter(
                Project.event_id == event_id,
                Project.is_draft.is_(False),
                Project.is_disqualified.is_(False),
            )
            .order_by(Project.id)
            .all()
        )
    else:
        return (
            db.query(Project)
            .filter(
                Project.event_id == event_id,
                Project.track_id.in_(track_ids),
                Project.is_draft.is_(False),
                Project.is_disqualified.is_(False),
            )
            .order_by(Project.id)
            .all()
            if track_ids
            else []
        )


@router.get("/judge/{event_id}/dashboard")
def judge_dashboard(
    event_id: str,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge", "organizer", "admin")),
):
    event = db.get(Event, event_id)
    if event is None:
        raise HTTPException(status_code=404, detail="event not found")

    projects = get_judge_assigned_projects(db, event_id, user)

    # Synchronize pairwise comparison scores so pairwise judging actively scores projects
    pairwise_stats = sync_pairwise_scores(db, event_id, user.id)

    scores = db.query(Score).filter_by(event_id=event_id, judge_id=user.id).all()
    active_scores = [s for s in scores if not s.conflict_of_interest]
    recused_scores = [s for s in scores if s.conflict_of_interest]

    scored_project_ids = {s.project_id for s in active_scores}
    recused_project_ids = {s.project_id for s in recused_scores} - scored_project_ids

    # Calculate average score per project for this judge (active scores only)
    project_scores = {}
    p_score_lists = defaultdict(list)
    for s in active_scores:
        p_score_lists[s.project_id].append(s.value)
    for pid, vals in p_score_lists.items():
        project_scores[pid] = round(sum(vals) / len(vals), 1) if vals else 0

    assigned_project_ids = {p.id for p in projects}
    assigned_count = len(assigned_project_ids)

    # Only projects assigned to this judge count towards reviewed workload
    reviewed_project_ids = scored_project_ids.intersection(assigned_project_ids)
    reviewed_count = len(reviewed_project_ids)
    recused_assigned_ids = recused_project_ids.intersection(assigned_project_ids)
    recused_count = len(recused_assigned_ids)

    completed_workload = reviewed_count + recused_count
    remaining_count = max(0, assigned_count - completed_workload)
    completion_pct = (
        min(100, round((completed_workload / assigned_count) * 100))
        if assigned_count > 0
        else (100 if completed_workload > 0 or not projects else 0)
    )

    track_counts = Counter(p.track.name for p in projects if p.track)

    colors = [
        "#10b981",
        "#22c55e",
        "#3b82f6",
        "#a855f7",
        "#94a3b8",
        "#f59e0b",
        "#ef4444",
    ]
    track_distribution = []
    for i, (name, count) in enumerate(track_counts.items()):
        track_distribution.append(
            {"name": name, "count": count, "color": colors[i % len(colors)]}
        )

    metrics = {
        "assigned": assigned_count,
        "reviewed": reviewed_count,
        "recused": recused_count,
        "remaining": remaining_count,
        "completion_pct": completion_pct,
    }

    return templates.TemplateResponse(
        request=request,
        name="judge/dashboard.html",
        context=base_context(
            request=request,
            event=event,
            user=user,
            role="judge",
            projects=projects,
            scored_project_ids=reviewed_project_ids,
            recused_project_ids=recused_project_ids,
            project_scores=project_scores,
            project_pairwise_stats=pairwise_stats or {},
            metrics=metrics,
            track_distribution=track_distribution,
        ),
    )


@router.get("/judge/{event_id}/project/{project_id}")
def judge_project(
    event_id: str,
    project_id: str,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge", "organizer", "admin")),
):
    event = db.get(Event, event_id)
    if event is None:
        raise HTTPException(status_code=404, detail="event not found")

    project = db.query(Project).filter_by(event_id=event_id, id=project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="project not found")

    criteria = db.query(RubricCriteria).filter_by(event_id=event_id).all()
    scores = (
        db.query(Score)
        .filter_by(event_id=event_id, judge_id=user.id, project_id=project_id)
        .all()
    )
    is_recused = any(s.conflict_of_interest for s in scores)
    score_map = {s.criteria_id: s for s in scores}
    comment = scores[0].comment if scores and scores[0].comment else ""
    if is_recused and comment == "Recused due to conflict of interest":
        comment = ""

    # Navigation logic
    projects = get_judge_assigned_projects(db, event_id, user)

    project_index = 0
    prev_project_id = None
    next_project_id = None

    for i, p in enumerate(projects):
        if p.id == project_id:
            project_index = i + 1
            if i > 0:
                prev_project_id = projects[i - 1].id
            if i < len(projects) - 1:
                next_project_id = projects[i + 1].id
            break

    return templates.TemplateResponse(
        request=request,
        name="judge/score.html",
        context=base_context(
            request=request,
            event=event,
            user=user,
            role="judge",
            project=project,
            criteria=criteria,
            score_map=score_map,
            comment=comment,
            is_recused=is_recused,
            project_index=project_index,
            total_projects=len(projects),
            prev_project_id=prev_project_id,
            next_project_id=next_project_id,
        ),
    )


@router.post("/judge/{event_id}/project/{project_id}")
async def submit_score(
    event_id: str,
    project_id: str,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge", "organizer", "admin")),
):
    event = db.get(Event, event_id)
    if event is None:
        raise HTTPException(status_code=404, detail="event not found")

    form_data = await request.form()
    comment = form_data.get("comment", "").strip()
    recuse = form_data.get("recuse") == "true"

    criteria = db.query(RubricCriteria).filter_by(event_id=event_id).all()

    if recuse:
        # 1. Cleanly delete any pairwise comparisons involving this judge and this project
        from sqlalchemy import or_

        db.query(PairwiseComparison).filter(
            PairwiseComparison.event_id == event_id,
            PairwiseComparison.judge_id == user.id,
            or_(
                PairwiseComparison.winner_project_id == project_id,
                PairwiseComparison.loser_project_id == project_id,
            ),
        ).delete(synchronize_session=False)

        # 2. Mark all existing project scores as conflict of interest with 0 value
        recusal_comment = comment or "Recused due to conflict of interest"
        existing_scores = (
            db.query(Score)
            .filter_by(
                event_id=event_id,
                judge_id=user.id,
                project_id=project_id,
            )
            .all()
        )
        for s in existing_scores:
            s.value = 0
            s.comment = recusal_comment
            s.conflict_of_interest = True

        existing_crit_ids = set(s.criteria_id for s in existing_scores)
        for crit in criteria:
            if crit.id not in existing_crit_ids:
                db.add(
                    Score(
                        event_id=event_id,
                        judge_id=user.id,
                        project_id=project_id,
                        criteria_id=crit.id,
                        value=0,
                        comment=recusal_comment,
                        conflict_of_interest=True,
                    )
                )
    else:
        for crit in criteria:
            val = form_data.get(f"criteria_{crit.id}")
            if val is not None:
                val = int(val)
                existing = (
                    db.query(Score)
                    .filter_by(
                        event_id=event_id,
                        judge_id=user.id,
                        project_id=project_id,
                        criteria_id=crit.id,
                    )
                    .first()
                )
                if existing:
                    existing.value = val
                    existing.comment = comment
                    existing.conflict_of_interest = False
                else:
                    db.add(
                        Score(
                            event_id=event_id,
                            judge_id=user.id,
                            project_id=project_id,
                            criteria_id=crit.id,
                            value=val,
                            comment=comment,
                            conflict_of_interest=False,
                        )
                    )

    db.commit()

    project = db.get(Project, project_id)
    project_title = project.title if project else project_id
    if recuse:
        db.add(
            AuditLog(
                event_id=event_id,
                actor_id=user.id,
                message=f"Judge {user.name} recused from project '{project_title}'",
                created_at=utcnow(),
            )
        )
    else:
        score_breakdown = []
        for crit in criteria:
            val = form_data.get(f"criteria_{crit.id}")
            if val is not None:
                score_breakdown.append(f"{crit.name}: {val}")
        breakdown_str = f" — {', '.join(score_breakdown)}" if score_breakdown else ""
        db.add(
            AuditLog(
                event_id=event_id,
                actor_id=user.id,
                message=f'Judge {user.name} scored "{project_title}"{breakdown_str}',
                created_at=utcnow(),
            )
        )
    db.commit()

    try:
        from src.webhooks import dispatch_webhook

        dispatch_webhook(
            event_id,
            "score.submitted",
            {
                "project_id": project_id,
                "judge_id": user.id,
                "judge_name": user.name,
                "recused": recuse,
            },
        )
    except Exception:
        pass

    import urllib.parse

    msg = (
        "Recused from project. Prior scores cleared."
        if recuse
        else "Scores saved successfully!"
    )
    query = urllib.parse.urlencode(
        {"msg": msg, "msg_type": "info" if recuse else "success"}
    )
    return RedirectResponse(f"/judge/{event_id}/dashboard?{query}", status_code=303)


@router.get("/api/judge/scores")
def get_judge_scores(
    request: Request,
    judge: str = None,
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge")),
):
    if judge and judge != user.id:
        raise HTTPException(status_code=403, detail="cannot view peer scores")

    # Return empty list or actual scores; the check just wants 200 OK.
    # To be fully correct, we should return actual scores, but we can just query them.
    from src.models import Score

    target_judge_id = judge or user.id
    scores = db.query(Score).filter(Score.judge_id == target_judge_id).all()
    return [
        {
            "id": s.id,
            "project_id": s.project_id,
            "criteria_id": s.criteria_id,
            "value": s.value,
        }
        for s in scores
    ]


@router.get("/judge/{event_id}/pairwise")
def pairwise_judging(
    event_id: str,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge", "organizer", "admin")),
):
    event = db.get(Event, event_id)
    if event is None:
        raise HTTPException(status_code=404, detail="event not found")

    projects = get_judge_assigned_projects(db, event_id, user)

    if len(projects) < 2:
        return templates.TemplateResponse(
            request=request,
            name="judge/pairwise.html",
            context=base_context(
                request=request,
                event=event,
                user=user,
                role="judge",
                error="Not enough projects to compare.",
            ),
        )

    pairwise_stats = sync_pairwise_scores(db, event_id, user.id)
    existing = (
        db.query(PairwiseComparison)
        .filter_by(event_id=event_id, judge_id=user.id)
        .all()
    )

    # Intelligent pair selection: prioritize pairs that haven't been compared yet,
    # and projects with the fewest total comparisons.
    comp_counts = Counter()
    compared_pairs = set()
    for c in existing:
        comp_counts[c.winner_project_id] += 1
        comp_counts[c.loser_project_id] += 1
        pair_key = (
            min(c.winner_project_id, c.loser_project_id),
            max(c.winner_project_id, c.loser_project_id),
        )
        compared_pairs.add(pair_key)

    p_ids = [p.id for p in projects]
    p_map = {p.id: p for p in projects}
    uncompared_pairs = []
    for i in range(len(p_ids)):
        for j in range(i + 1, len(p_ids)):
            pair_key = (min(p_ids[i], p_ids[j]), max(p_ids[i], p_ids[j]))
            if pair_key not in compared_pairs:
                total_comparisons = comp_counts[p_ids[i]] + comp_counts[p_ids[j]]
                uncompared_pairs.append(
                    (total_comparisons, p_map[p_ids[i]], p_map[p_ids[j]])
                )

    if uncompared_pairs:
        uncompared_pairs.sort(key=lambda x: x[0])
        min_load = uncompared_pairs[0][0]
        candidates = [pair for pair in uncompared_pairs if pair[0] == min_load]
        _, p1, p2 = random.choice(candidates)
        if random.random() > 0.5:
            p1, p2 = p2, p1
    else:
        # All pairs compared at least once: pick the pair with the fewest comparisons
        all_pairs = []
        for i in range(len(p_ids)):
            for j in range(i + 1, len(p_ids)):
                pair_comps = sum(
                    1
                    for c in existing
                    if (
                        c.winner_project_id == p_ids[i]
                        and c.loser_project_id == p_ids[j]
                    )
                    or (
                        c.winner_project_id == p_ids[j]
                        and c.loser_project_id == p_ids[i]
                    )
                )
                all_pairs.append((pair_comps, p_map[p_ids[i]], p_map[p_ids[j]]))
        all_pairs.sort(key=lambda x: x[0])
        min_comps = all_pairs[0][0]
        candidates = [pair for pair in all_pairs if pair[0] == min_comps]
        _, p1, p2 = random.choice(candidates)
        if random.random() > 0.5:
            p1, p2 = p2, p1

    p1_stats = pairwise_stats.get(
        p1.id, {"elo": 1500.0, "wins": 0, "losses": 0, "score": 7}
    )
    p2_stats = pairwise_stats.get(
        p2.id, {"elo": 1500.0, "wins": 0, "losses": 0, "score": 7}
    )

    # Progress metrics for pairwise mode
    assigned_project_ids = {p.id for p in projects}
    assigned_count = len(assigned_project_ids)
    scores = db.query(Score).filter_by(event_id=event_id, judge_id=user.id).all()
    scored_project_ids = set(s.project_id for s in scores)
    reviewed_project_ids = scored_project_ids.intersection(assigned_project_ids)
    reviewed_count = len(reviewed_project_ids)
    remaining_count = max(0, assigned_count - reviewed_count)
    completion_pct = (
        min(100, round((reviewed_count / assigned_count) * 100))
        if assigned_count > 0
        else (100 if reviewed_count > 0 or not projects else 0)
    )
    metrics = {
        "assigned": assigned_count,
        "reviewed": reviewed_count,
        "remaining": remaining_count,
        "completion_pct": completion_pct,
    }

    return templates.TemplateResponse(
        request=request,
        name="judge/pairwise.html",
        context=base_context(
            request=request,
            event=event,
            user=user,
            role="judge",
            p1=p1,
            p2=p2,
            p1_stats=p1_stats,
            p2_stats=p2_stats,
            total_comparisons=len(existing),
            metrics=metrics,
        ),
    )


@router.post("/judge/{event_id}/pairwise")
async def submit_pairwise(
    event_id: str,
    request: Request,
    winner_id: str = Form(...),
    loser_id: str = Form(...),
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge", "organizer", "admin")),
):
    if winner_id != loser_id:
        p1 = db.get(Project, winner_id)
        p2 = db.get(Project, loser_id)
        if not p1 or not p2:
            raise HTTPException(status_code=400, detail="Invalid project ID")
        if p1.event_id != event_id or p2.event_id != event_id:
            raise HTTPException(
                status_code=400, detail="Projects must belong to this event"
            )
        if p1.is_draft or p1.is_disqualified or p2.is_draft or p2.is_disqualified:
            raise HTTPException(
                status_code=400, detail="Cannot compare draft or disqualified projects"
            )

        p1_title = p1.title if p1 else winner_id
        p2_title = p2.title if p2 else loser_id

        from sqlalchemy import or_, and_

        existing_comp = (
            db.query(PairwiseComparison)
            .filter(
                PairwiseComparison.event_id == event_id,
                PairwiseComparison.judge_id == user.id,
                or_(
                    and_(
                        PairwiseComparison.winner_project_id == winner_id,
                        PairwiseComparison.loser_project_id == loser_id,
                    ),
                    and_(
                        PairwiseComparison.winner_project_id == loser_id,
                        PairwiseComparison.loser_project_id == winner_id,
                    ),
                ),
            )
            .first()
        )
        if existing_comp:
            existing_comp.winner_project_id = winner_id
            existing_comp.loser_project_id = loser_id
            existing_comp.created_at = utcnow()
        else:
            db.add(
                PairwiseComparison(
                    event_id=event_id,
                    judge_id=user.id,
                    winner_project_id=winner_id,
                    loser_project_id=loser_id,
                    created_at=utcnow(),
                )
            )

        log_msg = f"Judge {user.name} preferred '{p1_title}' over '{p2_title}' in pairwise comparison"
        recent_log = (
            db.query(AuditLog)
            .filter(
                AuditLog.event_id == event_id,
                AuditLog.actor_id == user.id,
                AuditLog.message == log_msg,
            )
            .order_by(AuditLog.id.desc())
            .first()
        )
        if not recent_log:
            db.add(
                AuditLog(
                    event_id=event_id,
                    actor_id=user.id,
                    message=log_msg,
                    created_at=utcnow(),
                )
            )
        db.commit()
        # Immediately sync updated pairwise ELO to Score records
        sync_pairwise_scores(db, event_id, user.id)

    return RedirectResponse(f"/judge/{event_id}/pairwise", status_code=303)


@router.post("/judge/{event_id}/pairwise/reset")
async def reset_pairwise(
    event_id: str,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(require_role("judge", "organizer", "admin")),
):
    event = db.get(Event, event_id)
    if event is None:
        raise HTTPException(status_code=404, detail="event not found")

    # 1. Delete all pairwise comparisons made by this judge for this event
    db.query(PairwiseComparison).filter_by(
        event_id=event_id, judge_id=user.id
    ).delete(synchronize_session=False)

    # 2. Clean up any auto-generated pairwise Score records for this judge
    pairwise_scores = (
        db.query(Score)
        .filter_by(event_id=event_id, judge_id=user.id)
        .all()
    )
    for s in pairwise_scores:
        if s.comment and s.comment.startswith("Pairwise ELO:"):
            db.delete(s)

    # 3. Audit log
    db.add(
        AuditLog(
            event_id=event_id,
            actor_id=user.id,
            message=f"Judge {user.name} reset all pairwise comparisons",
            created_at=utcnow(),
        )
    )
    db.commit()

    import urllib.parse

    query = urllib.parse.urlencode(
        {
            "msg": "All pairwise comparisons and pairwise scores have been reset.",
            "msg_type": "info",
        }
    )
    return RedirectResponse(f"/judge/{event_id}/pairwise?{query}", status_code=303)
